---
title: Máquina de Café - Diagrama de Estados
---
stateDiagram-v2
[*] --> Idle
Idle --> comprobarsisepuedehacercafe: Usuario pide café

comprobarsisepuedehacercafe --> comprobaragua: Comprobar agua
comprobaragua --> Agua: Agua disponible
Agua --> requisitosaprobados: Se puede pedir café
comprobaragua --> Error: Fallo al comprobar agua

comprobarsisepuedehacercafe --> comprobarazucar : Usuario pide azúcar
comprobarazucar --> Azucar: Azúcar disponible
comprobarazucar --> Error : Fallo al comprobar azúcar
Azucar --> requisitosaprobados: Se puede pedir café con azúcar

Azucar --> sinazucar: Cafe sin azúcar
sinazucar --> Error : Fallo al echar azucar

requisitosaprobados --> solicitarcafe: Se puede pedir café
requisitosaprobados --> Error: Fallo al comprobar requisitos

comprobarsisepuedehacercafe --> Error: Fallo al comprobar café
solicitarcafe --> echarazucar: Usuario pide azúcar
solicitarcafe --> sinazucar: Usuario pide café sin azúcar
echarazucar --> haciendocafe: Cafe con azúcar
sinazucar --> haciendocafe: Cafe sin azúcar

haciendocafe --> sirviendocafe: Café preparado (sirviendocafe('Nescafé'))
sirviendocafe --> Error: Fallo durante servicio
Idle --> Error: Error inesperado
haciendocafe --> Error: Fallo durante preparación
echarazucar --> Error: Fallo al echar azúcar
sirviendocafe --> echaravaso: "Echando el vaso"
echaravaso --> cogervaso: Esperando a coger el vaso
cogervaso --> Error: Fallo al coger vaso
echaravaso --> cogervaso: Vaso cogido
cogervaso --> limpiarmaquina:  Vaso cogido, se puede limpiar
limpiarmaquina --> Idle: Máquina reiniciada
limpiarmaquina --> Error: Fallo al limpiar
note right of Idle: Estado inicial. Espera orden para hacer café.
note right of Error: Contiene mensaje de error. Se limpia para volver a Idle.

