---
title: Máquina de Café - Diagrama de Flujo
---
stateDiagram-v2
[*] --> Idle
Idle --> comprobarsisepuedehacercafe: Usuario pide café

comprobarsisepuedehacercafe --> comprobaragua: Comprobar agua
agua --> Error : No hay agua, no se puede hacer café
comprobaragua --> Agua: Agua disponible
Agua --> requisitosaprobados
Agua --> Error : Fallo no hay agua no se puede hacer café
comprobaragua --> Error: Fallo al comprobar agua

comprobarsisepuedehacercafe --> comprobarazucar : Comprobar si hay azucar
comprobarazucar --> Azucar: Azúcar disponible
comprobarazucar --> Error : Fallo al comprobar azúcar
Azucar --> requisitosaprobados

requisitosaprobados --> comprobandoRequisitos

Azucar --> sinazucar: Cafe sin azúcar
sinazucar --> Error : Fallo al echar azucar

comprobandoRequisitos --> solicitandocafe: Se puede hacer cafe
comprobandoRequisitos --> Error: Fallo al comprobar requisitos
requisitosaprobados --> Error: Fallo al comprobar requisitos

comprobarsisepuedehacercafe --> Error: Fallo al comprobar café
solicitandocafe --> echandoazucar: Usuario pide azúcar
solicitandocafe --> sinazucar: Usuario pide café sin azúcar
echandoazucar --> haciendocafe: Cafe con azúcar
sinazucar --> haciendocafe: Cafe sin azúcar

haciendocafe --> sirviendocafe: Café preparado (sirviendocafe('Nescafé'))
sirviendocafe --> Error: Fallo durante servicio
Idle --> Error: Error inesperado
haciendocafe --> Error: Fallo durante preparación
echandoazucar --> Error: Fallo al echar azúcar
sirviendocafe --> echandoavaso: "Echando el vaso"
echandoavaso --> cogiendovaso: Esperando a coger el vaso
cogiendovaso --> Error: Fallo al coger vaso
echandoavaso --> cogiendovaso: Vaso cogido
cogiendovaso --> limpiandomaquina:  Vaso cogido, se puede limpiar
limpiandomaquina --> Idle: Máquina reiniciada
limpiandomaquina --> Error: Fallo al limpiar
note right of Idle: Estado inicial. Espera orden para hacer café.
note right of Error: Contiene mensaje de error. Se limpia para volver a Idle.

