---
title: Máquina de Café - Diagrama de Estados
---
stateDiagram-v2
[*] --> Idle
Idle --> solicitarcafe: Usuario pide café

solicitarcafe --> comprobaragua: Comprobar agua
comprobaragua --> Agua: Agua disponible
Agua --> Error: Fallo al comprobar agua
Agua --> solicitarcafe: Se puede pedir café
comprobaragua --> Error: Fallo al comprobar agua

solicitarcafe --> comprobarazucar : Usuario pide azúcar
comprobarazucar --> Azucar: Azúcar disponible
Azucar --> Error: Fallo al comprobar azúcar
Azucar --> solicitarcafe: Se puede pedir café con azúcar

solicitarcafe --> echarazucar: Usuario pide azúcar
echarazucar --> haciendocafe: Cafe con azúcar

solicitarcafe --> haciendocafe: Cafe sin azúcar → directo a hacer café
haciendocafe --> sirviendocafe: Café preparado (sirviendocafe('Nescafé'))
sirviendocafe --> Error: Fallo durante servicio
Idle --> Error: Error inesperado
haciendocafe --> Error: Fallo durante preparación
echarazucar --> Error: Fallo al echar azúcar
sirviendocafe --> echaravaso: "Echando el vaso"
echaravaso --> cogervaso: Esperando a coger el vaso
cogervaso --> Error: Fallo al coger vaso
echaravaso --> cogervaso: Vaso cogido
cogervaso --> limpiarmaquina:  Vaso cogido, se puede limpiar
limpiarmaquina --> Idle: Máquina reiniciada
limpiarmaquina --> Error: Fallo al limpiar
note right of Idle: Estado inicial. Espera orden para hacer café.
note right of Error: Contiene mensaje de error. Se limpia para volver a Idle.

